### PR TITLE
Fixed array changes

### LINKED ISSUE #17: `fixed_array` ctor prevents aggregate initialization
The presence of the two defined ctors prevents aggregate initialization of array values at the time of construction. Is this decision intentional, or are you open to removing these? Removing the two constructors defined here would be a breaking change, but warranted IMHO as it complicates porting existing codebases from std to rde.

https://github.com/msinilo/rdestl/blob/f416f643a256e1d975cde5b123b5f34d9167b4c0/fixed_array.h#L19-L25

### PR DESCRIPTION
**Pull request by StelioKontosXBL**
Fixes #17.

### CODE REVIEW

File: fixed_array.h [hunk 1]
```diff
@@ -47,11 +46,14 @@ class fixed_array
...
 	}
-
-private:
-	T	m_data[N];
 };
 
+#if RDE_HAS_CPP11
+// A condensed alias using standard container nomenclature
+template<typename T, size_t N>
+using array = fixed_array<T, N>;
```
Comment (StelioKontosXBL) [inline fixed_array.h:54]: I would be in favor of adopting `array<T,N>` as the actual name, given the fact that fixed allocation is a fundamental requirement for an array to begin with, along with being homogeneous, contiguous, etc. Your thoughts @msinilo?

**Comment by StelioKontosXBL** [comment]
In hindsight, I should've created this branch from your master, not my fork, so my readme changes and merge commits from the last pr don't muddle things up. I'll delete this branch and pr and resubmit a fresh one tomorrow (same applies for pr #19).
